"""
Tool: report_formatter_tool

Generates a structured Markdown competitor analysis report from collected data.
Optionally saves the report to disk.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from langchain_core.tools import tool

import config


def _enum_val(v):
    """Extract the string value from a potential enum."""
    return v.value if hasattr(v, 'value') else v


def _build_report(
    location: str,
    radius_km: float,
    competitors: list[dict],
    footfall_estimates: list[dict],
) -> str:
    """Build the full Markdown report string."""
    now = datetime.now().strftime("%B %d, %Y %H:%M")
    lines: list[str] = []

    # ── Header ──────────────────────────────────────────────
    lines.append(f"# Competitor Intelligence Report")
    lines.append(f"**Location:** {location}  ")
    lines.append(f"**Radius:** {radius_km} km  ")
    lines.append(f"**Generated:** {now}  ")
    lines.append(f"**Data Disclaimer:** All footfall figures are *estimates* derived from public proxy indicators.\n")

    # ── 1. Area Overview ────────────────────────────────────
    lines.append("## 1. Area Overview\n")
    lines.append(
        f"The analysis covers **{len(competitors)} clothing stores** within "
        f"a {radius_km} km radius of **{location}**. "
        f"The area shows a {'high' if len(competitors) >= 8 else 'moderate'} "
        f"density of fashion retail outlets, indicating "
        f"{'strong' if len(competitors) >= 8 else 'moderate'} competitive pressure.\n"
    )

    # ── 2. Competitor List ──────────────────────────────────
    lines.append("## 2. Competitor List\n")
    lines.append("| # | Store | Distance (km) | Type | Address |")
    lines.append("|---|-------|---------------|------|---------|")
    for i, c in enumerate(competitors, 1):
        lines.append(
            f"| {i} | {c['name']} | {c.get('distance_km', 'N/A')} | "
            f"{c.get('business_type', 'clothes')} | {c.get('address', 'N/A')} |"
        )
    lines.append("")

    # ── 3. Footfall Comparison ──────────────────────────────
    lines.append("## 3. Footfall Comparison\n")
    lines.append("| Store | Avg Footfall | Busiest Day | Quietest Day |")
    lines.append("|-------|-------------|-------------|-------------|")
    est_map = {e["competitor_name"]: e for e in footfall_estimates}
    for c in competitors:
        e = est_map.get(c["name"], {})
        avg = _enum_val(e.get('average_footfall', 'N/A'))
        lines.append(
            f"| {c['name']} | {avg} | "
            f"{e.get('busiest_day', 'N/A')} | {e.get('quietest_day', 'N/A')} |"
        )
    lines.append("")

    # ── 4. Peak Hour Analysis ───────────────────────────────
    lines.append("## 4. Peak Hour Analysis\n")
    for est in footfall_estimates[:5]:  # Top 5 for brevity
        lines.append(f"### {est['competitor_name']}")
        lines.append(f"_{est.get('weekly_pattern_summary', '')}_\n")
        if est.get("peak_hours"):
            lines.append("| Day | Time | Busyness | Level |")
            lines.append("|-----|------|----------|-------|")
            for slot in est["peak_hours"][:4]:
                level = _enum_val(slot['footfall_level'])
                lines.append(
                    f"| {slot['day']} | {slot['hour_start']}-{slot['hour_end']} | "
                    f"{'█' * (slot['relative_busyness'] // 10)} {slot['relative_busyness']}% | "
                    f"{level} |"
                )
            lines.append("")

    # ── 5. Strategic Takeaways ──────────────────────────────
    lines.append("## 5. Strategic Takeaways\n")

    if competitors:
        closest = min(competitors, key=lambda c: c.get("distance_km", 999))
        lines.append(f"- **Nearest competitor:** {closest['name']} ({closest.get('distance_km', 'N/A')} km)")
        lines.append(f"- **Total competitors in area:** {len(competitors)}")

    high_footfall = [e for e in footfall_estimates if _enum_val(e.get('average_footfall', '')) == 'High']
    medium_footfall = [e for e in footfall_estimates if _enum_val(e.get('average_footfall', '')) == 'Medium']
    if high_footfall:
        names = ", ".join(e["competitor_name"] for e in high_footfall)
        lines.append(f"- **High footfall stores ({len(high_footfall)}):** {names}")
    if medium_footfall:
        lines.append(f"- **Medium footfall stores:** {len(medium_footfall)}")

    lines.append("- **Peak competition window:** Evenings (17:00-21:00), especially Fri-Sun")
    lines.append("- **Opportunity window:** Weekday mornings (09:00-11:00) show lower footfall")
    lines.append("- **Recommendation:** Consider promotions during low-traffic periods to capture share")
    lines.append("")

    lines.append("---\n*Report generated by the Competitor Intelligence AI System.*")

    return "\n".join(lines)


@tool
def report_formatter_tool(location_name: str = "") -> str:
    """Generate a structured Markdown competitor analysis report.

    Call this AFTER competitor_fetch_tool and footfall_estimator_tool.
    It automatically uses the stored data from those tools.

    Args:
        location_name: Optional location name. If empty, uses last search.

    Returns:
        A full Markdown competitor analysis report.
    """
    from tools._store import get_search, get_last_location

    data = get_search(location_name)
    if not data:
        loc = get_last_location()
        if loc:
            return f"No data found for '{location_name}'. Last search was '{loc}'. Try that instead."
        return "No competitor data available. Please call competitor_fetch_tool first."

    competitors = data.get("competitors", [])
    radius_km = data.get("radius_km", config.DEFAULT_RADIUS_KM)
    area = data.get("search_area", location_name or "Unknown")
    footfall_estimates = data.get("footfall_estimates", [])

    if not competitors:
        return f"No competitors found for '{area}'. Cannot generate report."

    # If footfall not yet estimated, generate it now
    if not footfall_estimates:
        import random
        from tools.footfall_estimator import _estimate_one
        for c in competitors:
            distance = c.get("distance_km", 5.0)
            synth_reviews = max(300, int(5000 / (1 + distance * 1.5)) + random.randint(-400, 400))
            synth_rating = round(min(4.8, random.uniform(3.5, 4.5) + max(0, 0.5 - distance * 0.1)), 1)
            est = _estimate_one(
                name=c.get("name", "Unknown"),
                rating=c.get("rating") or synth_rating,
                review_count=c.get("review_count") or synth_reviews,
            )
            footfall_estimates.append(est.model_dump(mode="json"))

    report = _build_report(area, radius_km, competitors, footfall_estimates)

    # Save to file
    safe_name = area.lower().replace(" ", "_").replace(",", "")
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = config.REPORTS_DIR / f"report_{safe_name}_{ts}.md"
    path.write_text(report, encoding="utf-8")

    return report
